"""Prepare a mock-only Pi service bundle and inspect services without issuing commands."""

import argparse
import hashlib
import json
import re
import urllib.request
from http.client import HTTPException
from pathlib import Path, PurePosixPath
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
SERVICES = ("vision", "voice", "assistant", "arm-controller", "coordinator")
BUNDLE_FILES = ("runtime.json", "bench.json", "workbench-mock.service")


def read_json(path):
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def validate_runtime(config, *, mock_only=False):
    if config.get("mode") not in {"mock", "hardware"}:
        raise ValueError("Runtime mode must be mock or hardware")
    services = config.get("services")
    if not isinstance(services, dict) or set(services) != set(SERVICES):
        raise ValueError("Exactly the five backend service addresses are required")
    ports = set()
    for name, url in services.items():
        if not isinstance(url, str):
            raise ValueError(f"Invalid service address: {name}")
        parsed = urlsplit(url)
        if (
            parsed.scheme != "http"
            or parsed.hostname != "127.0.0.1"
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path
            or parsed.query
            or parsed.fragment
            or parsed.port is None
            or not 1024 <= parsed.port <= 65535
            or url != f"http://127.0.0.1:{parsed.port}"
        ):
            raise ValueError(f"Use http://127.0.0.1:PORT with an unprivileged port: {name}")
        if parsed.port in ports:
            raise ValueError("Service ports must be unique")
        ports.add(parsed.port)
    if mock_only:
        arm, camera = config.get("arm"), config.get("camera")
        if (
            config["mode"] != "mock"
            or not isinstance(arm, dict)
            or not isinstance(camera, dict)
            or arm.get("backend") != "pca9685"
            or camera.get("backend") != "picamera2"
        ):
            raise ValueError("Pi bundle requires mock mode, pca9685 arm and picamera2 camera")


def target_paths(root, user):
    # A deliberately small syntax avoids shell/systemd escaping and specifier expansion.
    if (
        not isinstance(root, str)
        or not re.fullmatch(r"/[A-Za-z0-9_./-]+", root)
        or ".." in root.split("/")
        or str(PurePosixPath(root)) != root
        or root == "/"
    ):
        raise ValueError("Pi root must be a normalized absolute Linux path without spaces")
    if not isinstance(user, str) or not re.fullmatch(r"[a-z_][a-z0-9_-]*", user) or user == "root":
        raise ValueError("Use an existing non-root Linux account name")
    return PurePosixPath(root) / ".runtime/pi-deployment", PurePosixPath(root) / ".runtime/pi-mock"


def render_unit(root, user):
    bundle, state = target_paths(root, user)
    return f"""# Generated by scripts/pi.py; review and start manually on the Pi.
[Unit]
Description=Workbench mock backends (manual start only)

[Service]
Type=simple
User={user}
WorkingDirectory={root}
Environment=WORKBENCH_ROOT={root}
Environment=WORKBENCH_CONFIG={bundle}/runtime.json
Environment=WORKBENCH_CALIBRATION={bundle}/bench.json
Environment=WORKBENCH_STATE_DIR={state}
Environment=WORKBENCH_MODE=mock
Environment=PYTHONUNBUFFERED=1
Environment=WEB_CONCURRENCY=1
ExecStartPre={root}/.venv/bin/python {root}/scripts/pi.py check --bundle {bundle}
ExecStart={root}/.venv/bin/python {root}/scripts/dev.py --backend-only --mode mock
Restart=no
KillMode=mixed
TimeoutStopSec=100
UMask=0077
StandardOutput=journal
StandardError=journal

# No [Install] section: no automatic boot startup is configured.
"""


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def prepare(output, root, user, config_path, bench_path):
    config, bench = read_json(config_path), read_json(bench_path)
    validate_runtime(config, mock_only=True)
    unit = render_unit(root, user)
    if not all(key in bench for key in ("tools", "vision", "arm")):
        raise ValueError("Bench configuration needs tools, vision and arm sections")
    output = Path(output)
    output.mkdir(parents=True, exist_ok=False)
    for name, value in (("runtime.json", config), ("bench.json", bench)):
        (output / name).write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    (output / "workbench-mock.service").write_text(unit, encoding="utf-8", newline="\n")
    manifest = {
        "schema_version": 1,
        "pi_root": root,
        "user": user,
        "mode": "mock",
        "files": {name: digest(output / name) for name in BUNDLE_FILES},
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return check_bundle(output)


def check_bundle(bundle):
    bundle = Path(bundle)
    manifest = read_json(bundle / "manifest.json")
    if manifest.get("schema_version") != 1 or manifest.get("mode") != "mock":
        raise ValueError("Unsupported or non-mock bundle")
    root, user = manifest.get("pi_root"), manifest.get("user")
    target, state = target_paths(root, user)
    expected_unit = render_unit(root, user)
    if manifest.get("files") != {name: digest(bundle / name) for name in BUNDLE_FILES}:
        raise ValueError("Bundle files changed; review and generate a new bundle")
    if (bundle / "workbench-mock.service").read_text(encoding="utf-8") != expected_unit:
        raise ValueError("Service unit does not match the mock-only template")
    validate_runtime(read_json(bundle / "runtime.json"), mock_only=True)
    bench = read_json(bundle / "bench.json")
    if not all(key in bench for key in ("tools", "vision", "arm")):
        raise ValueError("Bench configuration needs tools, vision and arm sections")
    return {
        "offline_checks_ok": True,
        "mode": "mock",
        "target_bundle": str(target),
        "state_directory": str(state),
        "pi_validation": "unperformed",
        "physical_readiness": "not established",
    }


class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def get_json(url, timeout):
    # Ignore proxy environment settings and refuse redirects outside the inspected endpoint.
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}), NoRedirect())
    request = urllib.request.Request(url, method="GET", headers={"Accept": "application/json"})
    with opener.open(request, timeout=timeout) as response:
        body = response.read(65537)
        if len(body) > 65536:
            raise ValueError("Health/status response exceeds 64 KiB")
        return json.loads(body)


def inspect_health(config, expected_mode, timeout=2, fetch=get_json):
    # Reuse canonical response validation; importing contracts cannot open devices.
    from workbench_contracts import TERMINAL, ArmStatus, Health, WorkbenchStatus

    validate_runtime(config)
    if expected_mode not in {"mock", "hardware"}:
        raise ValueError("Expected mode must be mock or hardware")
    results = {}
    for name in SERVICES:
        try:
            health = Health.model_validate(fetch(config["services"][name] + "/health", timeout))
            if health.service != name or health.mode != expected_mode:
                raise ValueError("Service identity or runtime mode mismatch")
            results[name] = {"responding": True, **health.model_dump()}
        except (OSError, ValueError, HTTPException) as exc:
            results[name] = {"responding": False, "ready": False, "detail": str(exc)}
    statuses = {}
    errors = {}
    for name, schema in (("arm-controller", ArmStatus), ("coordinator", WorkbenchStatus)):
        try:
            result = schema.model_validate(fetch(config["services"][name] + "/status", timeout))
            if name == "coordinator" and result.mode != expected_mode:
                raise ValueError("Coordinator status mode mismatch")
            statuses[name] = result.model_dump(mode="json")
        except (OSError, ValueError, HTTPException) as exc:
            errors[name] = str(exc)
    arm = statuses.get("arm-controller")
    coordinator = statuses.get("coordinator")
    services_ready = all(row["responding"] and row["ready"] for row in results.values())
    recovery = (
        arm["recovery_required"] or coordinator["recovery_required"]
        if arm and coordinator
        else None
    )
    idle = (
        arm["state"] in {"idle", "completed"}
        and (coordinator["operation"] is None or coordinator["operation"]["state"] in TERMINAL)
        if arm and coordinator
        else None
    )
    return {
        "checks_ok": services_ready and recovery is False and idle is True,
        "expected_mode": expected_mode,
        "services_ready": services_ready,
        "recovery_required": recovery,
        "workflow_idle": idle,
        "services": results,
        "status": statuses,
        "status_errors": errors,
        "physical_readiness": "not established by HTTP health or application status",
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    prepare_parser = commands.add_parser("prepare", help="write a new mock-only service bundle")
    prepare_parser.add_argument("--output", type=Path, required=True)
    prepare_parser.add_argument("--pi-root", required=True, help="absolute Linux checkout path")
    prepare_parser.add_argument("--user", required=True, help="existing non-root Pi account")
    prepare_parser.add_argument("--config", type=Path, default=ROOT / "config/development/pi.json")
    prepare_parser.add_argument(
        "--bench", type=Path, default=ROOT / "config/workbench/default.json"
    )
    check_parser = commands.add_parser(
        "check", help="check bundle files offline; no devices opened"
    )
    check_parser.add_argument("--bundle", type=Path, required=True)
    health_parser = commands.add_parser(
        "health", help="GET health/status only; never recover or retry"
    )
    health_parser.add_argument("--config", type=Path, default=ROOT / "config/development/pi.json")
    health_parser.add_argument("--expected-mode", choices=("mock", "hardware"), default="mock")
    health_parser.add_argument(
        "--timeout", type=float, default=2, help="seconds per GET (0 < n <= 10)"
    )
    args = parser.parse_args(argv)
    try:
        if args.command == "prepare":
            result = prepare(args.output, args.pi_root, args.user, args.config, args.bench)
        elif args.command == "check":
            result = check_bundle(args.bundle)
        else:
            if not 0 < args.timeout <= 10:
                raise ValueError("Timeout must be between 0 (exclusive) and 10 seconds")
            result = inspect_health(read_json(args.config), args.expected_mode, args.timeout)
    except (OSError, ValueError, TypeError) as exc:
        parser.error(str(exc))
    print(json.dumps(result, indent=2))
    return 0 if result.get("offline_checks_ok", result.get("checks_ok")) else 1


if __name__ == "__main__":
    raise SystemExit(main())
